CREATE DATABASE IF NOT EXISTS hospitaldb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hospitaldb;

-- BẢNG NGƯỜI DÙNG (ok)
DROP TABLE nguoidung;
CREATE TABLE IF NOT EXISTS nguoidung (
    MaNguoiDung INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen VARCHAR(100) NOT NULL,
    VaiTro ENUM('Admin','BacSi','LeTan') NOT NULL,
    Email VARCHAR(100),
    SoDienThoai VARCHAR(20) UNIQUE CHECK (SoDienThoai REGEXP '^[0-9]{10,11}$'),
    TrangThai BOOLEAN DEFAULT TRUE,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BẢNG BỆNH NHÂN (ok)
DROP TABLE benhnhan;
CREATE TABLE IF NOT EXISTS benhnhan (
    MaBenhNhan INT AUTO_INCREMENT PRIMARY KEY,
    CCCD VARCHAR(20) UNIQUE NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,       
    NgaySinh DATE NOT NULL,           
    GioiTinh ENUM('Nam','Nữ') NOT NULL,              
    SoDienThoai VARCHAR(20) UNIQUE CHECK (SoDienThoai REGEXP '^[0-9]{10,11}$'),           
    BHYT VARCHAR(20) NOT NULL,         
    DiaChi TEXT NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BẢNG BÁC SĨ
DROP TABLE bacsi;
CREATE TABLE IF NOT EXISTS bacsi (
    MaBacSi INT AUTO_INCREMENT PRIMARY KEY,
    MaNguoiDung INT NOT NULL UNIQUE,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR(10),
    CMNDCCCD VARCHAR(20),
    DiaChi NVARCHAR(255),
    KinhNghiem INT,
    ChuyenKhoa NVARCHAR(150),
    FOREIGN KEY (MaNguoiDung) REFERENCES nguoidung(MaNguoiDung) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BẢNG THUỐC (ok)
CREATE TABLE IF NOT EXISTS thuoc (
    MaThuoc INT AUTO_INCREMENT PRIMARY KEY,
    TenThuoc NVARCHAR(200) NOT NULL,
    DonViTinh NVARCHAR(50) NOT NULL,
    DonGia DECIMAL(18, 2) NOT NULL DEFAULT 0 CHECK (DonGia >= 0),
    SoLuongTon INT NOT NULL DEFAULT 0 CHECK (SoLuongTon >= 0),
    HangSanXuat NVARCHAR(200),
    CongDung NVARCHAR(500),
    NgayHetHan DATE,
    TrangThai BOOLEAN DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BẢNG DỊCH VỤ
CREATE TABLE IF NOT EXISTS dichvu (
    MaDichVu INT AUTO_INCREMENT PRIMARY KEY,
    TenDichVu NVARCHAR(200) NOT NULL,
    LoaiDichVu NVARCHAR(100) NOT NULL,
    DonGia DECIMAL(18, 2) NOT NULL DEFAULT 0 CHECK (DonGia >= 0),
    DonViTinh NVARCHAR(50),
    MoTa NVARCHAR(500),
    TrangThai BOOLEAN DEFAULT TRUE,
    INDEX (TenDichVu)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BẢNG PHÒNG
CREATE TABLE IF NOT EXISTS phong (
    MaPhong INT AUTO_INCREMENT PRIMARY KEY,
    TenPhong NVARCHAR(100) NOT NULL,
    LoaiPhong NVARCHAR(50) NOT NULL,
    Tang NVARCHAR(20),
    SoGiuong INT NOT NULL DEFAULT 0,
    SoGiuongTrong INT NOT NULL DEFAULT 0,
    GiaTien DECIMAL(18, 2) NOT NULL DEFAULT 0,
    TrangThai NVARCHAR(50) DEFAULT 'Hoạt động',
    MoTa NVARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- KIỂM TRA BẢNG
SELECT * FROM nguoidung;
SELECT * FROM benhnhan;